config/routes.rb
  Rails.application.routes.draw do
 
    namespace :admin do
      resources :articles
      resources :comments
      resources :users
  
      root to: "articles#index"
    end

    resources :articles do
      resources :comments
    end
 
    root 'welcome#index'
  
  
  get 'signup'  => 'users#new' 
  resources :users

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  
  has_secure_password
  
  validates :name, uniqueness: {case_sensitive: false}
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
      if session[:user_id]
        if User.find(session[:user_id]).name == 'admin'
          #Authorized
        else
          flash[:danger] = "You Are Not Authorized!"
          redirect_to '/'
        end
      else
        flash[:danger] = "You Are Not Authorized!"
        redirect_to '/'
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Article.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Article.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Comment.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Comment.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user 

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def require_user 
    redirect_to login_path unless current_user 
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, only: [:new, :edit, :create, :update, :destroy]
 
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @user = User.find(current_user.id)
    @article = @user.articles.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    @user = User.find(current_user.id)
    @article = @user.articles.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only: [:new, :edit, :create, :update, :destroy]
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    @user = User.find_by_name(params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "Login successfully!"
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      flash[:danger] = "Wrong Name or Password!"
      redirect_to login_path
    end 
  end
  
  def destroy 
    flash[:success] = "Logged out!"
    session[:user_id] = nil 
    redirect_to articles_path 
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params) 
    if @user.save 
      flash[:success] = "Your user is created!"
      session[:user_id] = @user.id 
      redirect_to '/' 
    else 
      flash[:danger] = "Name is already taken, please choose another name."
      redirect_to '/signup' 
    end 
  end

  
  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
    @cmts = @articles.sort_by{|f| f.comments.size}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <div class="well">
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
     
      <p>
        <%= f.label :text %><br>
        <%= f.text_area :text %>
      </p>
     
      <%= f.submit "Create Article",  class: "btn btn-lg btn-success" %>
 </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <div class="well">
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
     
      <p>
        <%= f.label :text %><br>
        <%= f.text_area :text %>
      </p>
     
      <%= f.submit "Edit Article",  class: "btn btn-lg btn-success" %>
 </div>
<% end %>
 
<%= link_to 'Back', article_path(@article), class: "btn btn-warning" %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New article', new_article_path, class: "btn btn-lg btn-success" %>
  <h2>Click an article title to view its comments</h2><hr>
 
  <% @articles.each do |article| %>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to article.title, article_path(article) %> - <em><%= User.find(article.user_id).name %></em></h3>
      </div>
      <div class="panel-body">
        <%= article.text %><hr>
        <% if current_user %>
          <% if current_user.id == article.user_id %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-sm btn-warning" %>
            <%= link_to 'Destroy', article_path(article), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        <% end %>  
      </div>
    </div>
  <% end %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path, class: "btn btn-warning" %>

app/views/articles/show.html.erb
<div class="container">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= @article.title %> </strong>- <em><%= User.find(@article.user_id).name %></em></h3>
    </div>
    <div class="panel-body">
      <%= @article.text %>
    </div>
  </div>
  <% if current_user %>
    <% if current_user.id == @article.user_id %>
      <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-sm btn-success" %>
    <% end %>
  <% end %>  
  <%= link_to 'Back', articles_path, class: "btn btn-sm btn-warning" %>
</div>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<% if current_user %> 
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %>

app/views/comments/_comment.html.erb
<div class="well">
  <strong><%= User.find(comment.user_id).name %>:</strong>
  <%= comment.body %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="well">
    <%= f.label :Comment %><br>
    <%= f.text_area :body %>
    
    <%= f.submit "Create Comment",  class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar_in.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <dev class="container">
      <%= link_to "My Blog", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <div class="nav-item">
        <%= link_to "Welcome, " + current_user.name, "", class: "btn btn-default btn-success" %>
      </div>
      <div class="nav-item">
        <%= link_to "Log out", logout_path, method: "delete", class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav-item">
        <%= link_to "View Articles", articles_path, class: "btn btn-default btn-warning" %>
      </div>
    </dev>
  </header>

app/views/layouts/_navbar_out.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <dev class="container">
      <%= link_to "My Blog", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <div class="nav-item">
        <%= link_to "Sign up", signup_path, class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav-item">
        <%= link_to "Log in", login_path, class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav-item">
        <%= link_to "View Articles", articles_path, class: "btn btn-default btn-warning" %>
      </div>
    </dev>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QTD Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  
  <body>
    <% if current_user %>
      <% if current_user.name == 'admin' %>
        <%= link_to "Admin Page", admin_root_path, class: "btn btn-lg btn-danger" %>
      <% end %>
    <% end %>
    
    <% if current_user %>
      <%= render '/layouts/navbar_in' %>
    <% else %> 
      <%= render '/layouts/navbar_out' %>
    <% end %>
  
    <%= render 'layouts/messages' %>
    <%= yield %>
  
  </body>
</html>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="form">
      <h1>Sign Up</h1>
  
      <%= form_for(@user) do |f| %>
        <%= f.text_field :name, :placeholder => "UserName" %>
        <%= f.password_field :password, :placeholder => "Password" %>
        <%= f.submit "Create Account",  class: "btn btn-lg btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
  <div class="center jumbotron">
    <h1>Welcome <%= current_user.name %>!</h1>
    <%= link_to 'View all articles', articles_path,  class:"btn btn-lg btn-success"  %>
  </div>
<% else %> 
  <div class="center jumbotron">
    <h1>Welcome!</h1>
    <h2>Signup or Login to create, view and comment on the articles.</h2>
    <%= link_to 'Sign Up Now!', signup_path,  class:"btn btn-lg btn-success"  %>
  </div>
<% end %>

<div id="one">
  <div>
    <div class="well" id="billboard">
      <h2 style="margin: 0 0 10 0"><strong>Top comment articles</strong></h2>
      <ul class="list-group">
        <% @cmts.reverse.first(10).each do |f| %>
          <li class="list-group-item ">
            <span class="badge"><%= f.comments.size %> Comments</span>
            <%= link_to f.title, article_path(f), style: "color:#009900" %> - <em><%= User.find(f.user_id).name %></em>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div id="two">
  <div>
    <div class="well" id="billboard">
      <h2 style="margin: 0 0 10 0"><strong>Top recent articles</strong></h2>
      <ul class="list-group">
        <% @articles.sort_by(&:created_at).reverse.first(10).each do |f| %>
          <li class="list-group-item ">
            <span class="badge"><%= time_ago_in_words(f.created_at) %> ago</span>
            <%= link_to f.title, article_path(f), style: "color:#009900" %> - <em><%= User.find(f.user_id).name %></em>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>